config/routes.rb
Rails.application.routes.draw do
 

  root 'staticpages#home' 
  
  get 'staticpages/home' => 'staticpages#home' 
  get 'staticpages/link' => 'https://www.instagram.com/?hl=ja'
  

  
  resources 'users'

  delete 'users/:id/destroy' => 'users#destroy'

  post 'users/:id' => 'users#show'
  
  post 'users/new' => 'users#create'
  
  #####
  get 'users/:id/edit' => 'users#edit'
  patch 'users/:id/edit' => 'users#edit'
  
  ####
  
 
  get 'sessions/new' => 'sessions#new'
  post 'sessions/new' => 'sessions#create'
  get 'sessions/destroy' => 'sessions#destroy'
  
  
  
  get 'microposts/newpost' => 'microposts#new'
  post 'microposts/newpost' => 'microposts#create'
 
  
  get 'memo/memo' => 'memo#new'
  post 'memo/memo' => 'memo#create'
  get 'memo/show' => 'memo#show'
  
  resources 'microposts'
  get 'microposts/destroy' => 'microposts#destroy'
 
  
  get 'users/follow' => 'users#follow'
  

  
  post 'users/:id/following' => 'users#following'
  
  
  get 'information/home' => 'information#home'
  
  resources :users do
    member do
      get :following, :followers
    end
  end


  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/memo.rb
class Memo < ApplicationRecord
end

app/controllers/memo_controller.rb
class MemoController < ApplicationController
    
    def new
        
        @memo = Memo.new
    end
    
    def create
        @memo = Memo.create(memo_params)
        if @memo.save
            flash[:success] = "Micropost saved!"
            redirect_to memo_show_path
            @feed_items = []
        else
            render 'memo/new'
        end
    end
    
    def show
        @shows = Memo.where(params[:content])
    end
    
    def micropost
        
    end
    
    private
    def memo_params
        params.require(:memo).permit(:id, :content, :user_id, :created_at, :updated_at)
    end
end

app/helpers/memo_helper.rb
module MemoHelper
end

app/views/memo/new.html.erb
<%= render 'layouts/header'%>

<main>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <h1>
          
            <%= current_user.name %>
          </h1>
        </section>
        <section class="stats">
          <%= render 'shared/stat' %>
        </section>
        <% if !ensure_correct_user %>
          <def>
            <%= link_to "edit", edit_user_path(current_user) %>
          </def>
        <% end %>
      </aside>
      <%= link_to "保存一覧", memo_show_path %>
      <%= form_with model: @memo, url: memo_memo_path do |f| %>
          <%= render 'shared/error_messages', object: f.object %>  
          
          <%= f.hidden_field :user_id, :value => current_user.id %>
          <%= f.text_area :content, class: 'form-control', placeholder: "Compose new micropost..." %>
          <%= f.submit "memo", class: "btn btn-primary" %>
  
      <% end %>
      
      
</main>

app/views/memo/show.html.erb
<%= render 'layouts/header'%>

<main>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <h1>
          
            <%= current_user.name %>
          </h1>
        </section>
        <section class="stats">
          <%= render 'shared/stat' %>
        </section>
        <% if !ensure_correct_user %>
          <def>
            <%= link_to "edit", edit_user_path(current_user) %>
          </def>
        <% end %>
      </aside>
      
      <%= @shows.each do |show|%>
        <div>
          <h3>
              <%= show.id%>
          </h3>
            
          <div>
              <%= show.content%>
             
              <%= link_to "toukou",microposts_newpost_path(content: show.content, authenticity_token: form_authenticity_token), method: :post %>
          </div>
        </div>
      <% end%>
    </div>
</main>