config/routes.rb
Rails.application.routes.draw do
 

  root 'staticpages#home' 
  
  get 'staticpages/home' => 'staticpages#home' 
  get 'staticpages/link' => 'https://www.instagram.com/?hl=ja'
  

  
  resources 'users'

  delete 'users/:id/destroy' => 'users#destroy'

  post 'users/:id' => 'users#show'
  
  post 'users/new' => 'users#create'
  
  #####
  get 'users/:id/edit' => 'users#edit'
  patch 'users/:id/edit' => 'users#edit'
  
  ####
  
 
  get 'sessions/new' => 'sessions#new'
  post 'sessions/new' => 'sessions#create'
  get 'sessions/destroy' => 'sessions#destroy'
  
  
  
  get 'microposts/newpost' => 'microposts#new'
  post 'microposts/newpost' => 'microposts#create'
 
  
  get 'memo/memo' => 'memo#new'
  post 'memo/memo' => 'memo#create'
  get 'memo/show' => 'memo#show'
  
  resources 'microposts'
  get 'microposts/destroy' => 'microposts#destroy'
 
  
  get 'users/follow' => 'users#follow'
  

  
  post 'users/:id/following' => 'users#following'
  
  
  get 'information/home' => 'information#home'
  
  resources :users do
    member do
      get :following, :followers
    end
  end


  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
    if logged_in?
    
      @micropost  = Micropost.all
      @feed_items = Micropost.all.page(params[:page])
    end
  end
  def login
  end
  def show 
  end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper

end

app/views/staticpages/_home_post.html.erb
        <!-- Project One -->
        <% @feed_items.each do |feed_item|%>
          <div class="row">
            <div class="col-md-7">
              <a href="#">
                <img class="img-fluid rounded mb-3 mb-md-0" src="http://placehold.it/700x300" alt="">
              </a>
            </div>
            <div class="col-md-5">
              
              <h3>
                <%= link_to "#{feed_item.id}" ,user_path("#{feed_item.user_id}")%>
              </h3>
              
              <p><%=feed_item.content%></p>
              <a class="btn btn-primary" href="#"><%= feed_item.id%></a>
            </div>
            
          </div>
          <!-- /.row -->
    
          <hr>
        <% end %>

app/views/staticpages/contact.html.erb
<h1>Staticpages#contact</h1>
<p>Find me in app/views/staticpages/contact.html.erb</p>

app/views/staticpages/help.html.erb
<h1>Staticpages#help</h1>
<p>Find me in app/views/staticpages/help.html.erb</p>

app/views/staticpages/home.html.erb
  <%= render 'layouts/header'%>
   <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  
  <main>
    <% if logged_in? %> 
      <div class="container">
        <!-- Page Heading -->
        <h1 class="my-4">Page Heading
          <small>Secondary Text</small>
        </h1>
        
        <!-- Content -->
        <%= render 'staticpages/home_post'%>
  
        <%= paginate @feed_items %>
        
      </div>
      <!-- /.container -->
      <div>
        <% if current_user %>
            <%= puts "aaaa"%>
          <% else %>
            <%= puts "bbbb"%>
          <% end %> 
        <h1>
          aaaaaaaa
        </h1>
        <!--- signin link --->
        <h2>
          <%= link_to 'signin', new_user_path %>
        </h2>
        <!--- information link --->
        <h2>
          <%= link_to 'information', information_home_path %>
        </h2>
      </div>
    <% else %>
      <div class="col-md-8">
        <h3>Micropost Feed</h3>
        <%= render 'shared/feed' %>
      </div>
      
      <div>
        <h1><%= link_to "SignIn", new_user_path %></h1>
      </div>
      <div>
        <% if current_user %>
            <%= puts "aaaa"%>
          <% else %>
            <%= puts "bbbb"%>
          <% end %>
        <h1>
          bbbbbb
        </h1>
      </div>

      
    <% end %>
   
    <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  
   
  </main>
  