config/routes.rb
Rails.application.routes.draw do
 

  root 'staticpages#home' 
  
  get 'staticpages/home' => 'staticpages#home' 
  get 'staticpages/link' => 'https://www.instagram.com/?hl=ja'
  

  
  resources 'users'

  delete 'users/:id/destroy' => 'users#destroy'

  post 'users/:id' => 'users#show'
  
  post 'users/new' => 'users#create'
  
  #####
  get 'users/:id/edit' => 'users#edit'
  patch 'users/:id/edit' => 'users#edit'
  
  ####
  
 
  get 'sessions/new' => 'sessions#new'
  post 'sessions/new' => 'sessions#create'
  get 'sessions/destroy' => 'sessions#destroy'
  
  
  
  get 'microposts/newpost' => 'microposts#new'
  post 'microposts/newpost' => 'microposts#create'
 
  
  get 'memo/memo' => 'memo#new'
  post 'memo/memo' => 'memo#create'
  get 'memo/show' => 'memo#show'
  
  resources 'microposts'
  get 'microposts/destroy' => 'microposts#destroy'
 
  
  get 'users/follow' => 'users#follow'
  

  
  post 'users/:id/following' => 'users#following'
  
  
  get 'information/home' => 'information#home'
  
  resources :users do
    member do
      get :following, :followers
    end
  end


  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="ja">
 <head>
  <meta charset="utf-8">
   <title>Post_pict_App</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">  
  
   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


  </head>
<!-- Page Content -->
<% if logged_in? %>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">BONZI</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to("Home", staticpages_home_path, {class: "nav-link"})%>
           
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            
                <ul>
                  <li class="dropdown-item" ><%= link_to"profile" , users_path %></li>
                  
                  
                  <li class="dropdown-item" > <%= link_to "log_out", sessions_destroy_path %></li>
                </ul>
            
            </div>
          </li>
          
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <li class="btn btn-outline-success my-2 my-sm-0"><%= link_to"NewPost" ,microposts_newpost_path  %> </li>
        </form>
      </div>
    </nav>
  </header>
<% else %>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">BONZI</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to("Home", staticpages_home_path, {class: "nav-link"})%>
           
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <ul>
                  <li class="dropdown-item" ><%= link_to"login" , sessions_new_path%></li>
                  
                  <li class="dropdown-item" ><%= link_to"signin" ,new_user_path %></li>
                </ul>
            
            </div>
          </li>
          
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <li class="btn btn-outline-success my-2 my-sm-0"><%= link_to"NewPost" ,microposts_newpost_path  %> </li>
        </form>
      </div>
    </nav>
  </header>
<% end %>

  <!-- flash-message -->
  <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  
  <%= debug(params) if Rails.env.development? %>
  
  
   <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostpictApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>